[tool.black]
line-length = 120

[tool.poetry]
name = "heimdall"
version = "0.1.0"
description = "Systems monitoring service"
authors = ["Aleksander Skraastad <myth@overflow.no>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
uvicorn = "^0.23.2"
fastapi = "^0.101.0"
databases = "^0.7.0"
aiosqlite = "^0.19.0"
python-decouple = "^3.8"
aiohttp = "^3.8.5"
python-dateutil = "^2.8.2"
aiosmtplib = "^3.0.1"

[tool.poetry.group.dev.dependencies]
black = "^23.7.0"
pylint = "^2.17.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
