[tool.black]
line-length = 120

[tool.poetry]
name = "heimdall"
version = "0.1.0"
description = "Systems monitoring service"
authors = ["Aleksander Skraastad <myth@overflow.no>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
uvicorn = "0.26"
fastapi = "^0.109.2"
databases = "^0.8.0"
aiosqlite = "^0.19.0"
python-decouple = "^3.8"
aiohttp = "^3.9.3"
python-dateutil = "^2.8.2"
aiosmtplib = "^3.0.1"

[tool.poetry.group.dev.dependencies]
black = "^24.1.1"
pylint = "^3.0.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
